/**
 * "Real" fixtures: genuine Agent Server protocol payloads lifted verbatim
 * from the OpenHands repo at the pinned commit
 * `380fd839d6bcb1f9e1674ab0ff5c0225705118e8` — not authored by this spike.
 * Each entry's comment cites its exact upstream source file.
 *
 * Search performed (see MANIFEST.md "Fixture sourcing" row for the full
 * account): `src/mocks/` (MSW request handlers — settings/auth/git/etc.,
 * none carry an OpenHandsEvent[] history), `src/fixtures/` (2 files with
 * complete, realistic `OpenHandsEvent[]` conversations — used below),
 * any `.test.tsx` file under `src/` (unit test factories — one item below, `get-event-content.test.tsx`,
 * has a complete malformed-event object used verbatim in an assertion),
 * `tests/e2e/` (Playwright specs + a mock LiteLLM HTTP server — LLM
 * response bodies, not frontend event-stream fixtures, so nothing usable
 * there). No genuine upstream fixture covering `ExecuteBashAction`/
 * `TerminalAction` or `FinishAction` was found anywhere in the checkout —
 * those 2 entries below are hand-constructed from the real
 * `types/agent-server/core/base/action.ts` / `observation.ts` field shapes
 * (traced above) and are explicitly labeled as such, not presented as
 * "genuine" the way the other 5 are.
 */
import type { ExecutionEvent } from "./execution-events.synthetic";

const EXEC_ID = "exec-upstream-real-0001";

/**
 * Genuine, verbatim from upstream
 * `src/fixtures/canvas-demo-conversation.ts` @ 380fd839d6bcb1f9e1674ab0ff5c0225705118e8
 * (`CANVAS_DEMO_EVENTS`, minus its 2nd MessageEvent — split out below —
 * field values copied exactly, only the `ExecutionEvent` envelope
 * (`id`/`executionId`/`occurredAt`/`createdAt`/`kind`) is this spike's own).
 */
export const UPSTREAM_REAL_EVENTS: Record<string, ExecutionEvent> = {
  canvasDemoUserMessage: {
    // Envelope `id` matches the genuine upstream event id (`canvas-demo-user`)
    // rather than a spike-authored label — needed so `action_id` linkage on
    // the paired action/observation below (also genuine upstream ids)
    // resolves the same way AtherNull's real `pairActionsWithObservations`
    // expects: by `ExecutionEvent.id`, not by array position.
    id: "canvas-demo-user",
    executionId: EXEC_ID,
    kind: "MessageEvent",
    occurredAt: "2026-07-29T12:00:00.000Z",
    createdAt: "2026-07-29T12:00:00.000Z",
    payload: {
      id: "canvas-demo-user",
      timestamp: "2026-07-29T12:00:00.000Z",
      source: "user",
      llm_message: {
        role: "user",
        content: [
          { type: "text", text: "Create a concise project canvas as a Markdown report." },
        ],
      },
      activated_skills: [],
      extended_content: [],
    },
  },

  canvasDemoFileEditorAction: {
    id: "canvas-demo-action",
    executionId: EXEC_ID,
    kind: "ActionEvent",
    occurredAt: "2026-07-29T12:00:01.000Z",
    createdAt: "2026-07-29T12:00:01.000Z",
    payload: {
      id: "canvas-demo-action",
      timestamp: "2026-07-29T12:00:01.000Z",
      source: "agent",
      thought: [],
      thinking_blocks: [],
      action: {
        kind: "FileEditorAction",
        command: "create",
        path: "canvas.md",
        file_text:
          "# Agent Canvas Demo\n\nThis report was generated by the agent and opened from the file chip in chat.\n\n## Release snapshot\n\n| Area | Status | Next step |\n| --- | --- | --- |\n| Conversation UX | Ready | Validate the drawer flow |\n| Markdown preview | Ready | Review rich rendering |\n| Accessibility | Ready | Confirm keyboard navigation |\n\n## Highlights\n\n- The artifact stays in the conversation workspace.\n- The chat chip is the compact entry point.\n- The Files drawer provides the full rich Markdown view.",
        old_str: null,
        new_str: null,
        insert_line: null,
        view_range: null,
      },
      tool_name: "file_editor",
      tool_call_id: "canvas-demo-tool-call",
      tool_call: {
        id: "canvas-demo-tool-call",
        type: "function",
        function: {
          name: "file_editor",
          arguments: JSON.stringify({ command: "create", path: "canvas.md" }),
        },
      },
      llm_response_id: "canvas-demo-response",
      security_risk: "LOW",
    },
  },

  canvasDemoFileEditorObservation: {
    id: "canvas-demo-observation",
    executionId: EXEC_ID,
    kind: "ObservationEvent",
    occurredAt: "2026-07-29T12:00:02.000Z",
    createdAt: "2026-07-29T12:00:02.000Z",
    payload: {
      id: "canvas-demo-observation",
      timestamp: "2026-07-29T12:00:02.000Z",
      source: "environment",
      tool_name: "file_editor",
      tool_call_id: "canvas-demo-tool-call",
      action_id: "canvas-demo-action",
      observation: {
        kind: "FileEditorObservation",
        command: "create",
        output: "Created canvas.md",
        path: "canvas.md",
        prev_exist: false,
        old_content: null,
        // Truncated vs. upstream's full markdown for readability here; the
        // action's file_text above carries the full genuine content.
        new_content: "# Agent Canvas Demo\n...(see the paired action's file_text)",
        error: null,
        // NOTE (see MANIFEST.md "Fixture sourcing / parser gap" row): unlike
        // AtherNull's own synthetic fixtures, this real upstream
        // FileEditorObservation has no `content` array — only `output`.
        // AtherNull's real `parseToolCall()` (apps/web/lib/execution-events.ts)
        // reads `obsBody.content` for the file-editor `summary` field, which
        // this real shape leaves `null` for. That's a genuine small gap the
        // validation script below surfaces, not a bug introduced by this spike.
      },
    },
  },

  canvasDemoAgentMessage: {
    id: "canvas-demo-agent",
    executionId: EXEC_ID,
    kind: "MessageEvent",
    occurredAt: "2026-07-29T12:00:03.000Z",
    createdAt: "2026-07-29T12:00:03.000Z",
    payload: {
      id: "canvas-demo-agent",
      timestamp: "2026-07-29T12:00:03.000Z",
      source: "agent",
      llm_message: {
        role: "assistant",
        content: [
          { type: "text", text: "I generated the project canvas. Open it from the file chip above." },
        ],
      },
      activated_skills: [],
      extended_content: [],
    },
  },

  /**
   * Genuine, verbatim from upstream
   * `src/fixtures/table-demo-conversation.ts` @ 380fd839d6bcb1f9e1674ab0ff5c0225705118e8
   * (`TABLE_DEMO_EVENTS[1]`, the agent's wide-GFM-table reply).
   */
  tableDemoAgentMessage: {
    id: "real-5-table-demo-agent-message",
    executionId: EXEC_ID,
    kind: "MessageEvent",
    occurredAt: "2026-06-23T12:01:00.000Z",
    createdAt: "2026-06-23T12:01:00.000Z",
    payload: {
      id: "table-demo-agent-1",
      timestamp: "2026-06-23T12:01:00.000Z",
      source: "agent",
      llm_message: {
        role: "assistant",
        content: [
          {
            type: "text",
            text:
              "Here is a wide comparison table. Scroll horizontally to read every column:\n\n| Feature | OpenHands | Claude Code | Codex | Gemini CLI | Cursor | Windsurf | Cline | Aider | Devin | Continue |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| CLI | Yes | Yes | Yes | Yes | IDE | IDE | IDE | Terminal | Cloud | IDE |\n| MCP support | Yes | Yes | Partial | Partial | Yes | Yes | Yes | No | Yes | Yes |\n| Local models | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | No | Yes |\n| Browser tools | Yes | Yes | Yes | Limited | Yes | Yes | Yes | No | Yes | Yes |\n| Git integration | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes |\n| Best for | General coding | Anthropic stack | OpenAI stack | Google stack | IDE users | IDE users | VS Code | Terminal | Autonomous | IDE users |",
          },
        ],
      },
      activated_skills: [],
      extended_content: [],
    },
  },

  /**
   * Genuine, verbatim from upstream
   * `src/components/conversation-events/chat/event-content-helpers/get-event-content.test.tsx`
   * @ 380fd839d6bcb1f9e1674ab0ff5c0225705118e8 — the "extracts an action name
   * from an action-like server event" test case's `event` object (their own
   * example of a malformed/partial ActionEvent-shaped payload: missing
   * `thought`, `tool_name`, `tool_call_id`, etc.). Used upstream to assert
   * `getEventContent()` degrades to an uppercased kind name instead of
   * crashing — exactly the fallback behavior this spike's fixture (9) also
   * exercises with a synthetic example.
   */
  partialMalformedAction: {
    id: "real-6-partial-malformed-action",
    executionId: EXEC_ID,
    kind: "ActionEvent",
    occurredAt: "2026-01-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    payload: {
      id: "partial-action",
      timestamp: "2026-01-01T00:00:00.000Z",
      source: "agent",
      action: { kind: "SwitchLLMAction" },
    },
  },

  /**
   * NOT from an upstream fixture file (see the file-level comment above for
   * the search performed) — hand-constructed to real field shapes traced
   * from `types/agent-server/core/base/action.ts` / `observation.ts` so this
   * spike's "real" set still covers a terminal action+observation pair.
   */
  handConstructedTerminalAction: {
    id: "real-7-hand-constructed-terminal-action",
    executionId: EXEC_ID,
    kind: "ActionEvent",
    occurredAt: "2026-01-02T00:00:00.000Z",
    createdAt: "2026-01-02T00:00:00.000Z",
    payload: {
      tool_name: "terminal",
      thought: [],
      action: {
        kind: "ExecuteBashAction",
        command: "pytest tests/test_health.py -q",
        is_input: false,
        timeout: null,
        reset: false,
      },
    },
  },
  handConstructedTerminalObservation: {
    id: "real-7-hand-constructed-terminal-observation",
    executionId: EXEC_ID,
    kind: "ObservationEvent",
    occurredAt: "2026-01-02T00:00:01.000Z",
    createdAt: "2026-01-02T00:00:01.000Z",
    payload: {
      action_id: "real-7-hand-constructed-terminal-action",
      observation: {
        kind: "ExecuteBashObservation",
        content: [{ type: "text", text: "1 passed in 0.12s" }],
        command: "pytest tests/test_health.py -q",
        exit_code: 0,
        error: false,
        timeout: false,
      },
    },
  },

  /**
   * NOT from an upstream fixture file — hand-constructed (see above) to
   * cover a FinishAction (agent-server-adapter.py's execution completion
   * signal, per apps/web/lib/execution-events.ts's comment on
   * `parseMessage`).
   */
  handConstructedFinishAction: {
    id: "real-8-hand-constructed-finish-action",
    executionId: EXEC_ID,
    kind: "ActionEvent",
    occurredAt: "2026-01-03T00:00:00.000Z",
    createdAt: "2026-01-03T00:00:00.000Z",
    payload: {
      tool_name: "finish",
      thought: [],
      action: {
        kind: "FinishAction",
        message: "Task complete: the wide comparison table renders correctly.",
      },
    },
  },
};

export const UPSTREAM_REAL_EVENTS_LIST: ExecutionEvent[] = Object.values(
  UPSTREAM_REAL_EVENTS,
);
